# Site settings
title: Treehouse Installation Guides
email: dave@teamtreehouse.com
description: Installation guides for common application development tools. 
baseurl: "/installation-guides"
url: "treehouse.github.io/installation-guides/" # the base hostname & protocol for your site
twitter_username: treehouse
github_username:  treehouse
collections:
  windows:
    layout: page
    output: true
  mac:
    layout: page
    output: true
  linux:
    layout: page
    output: true

# Build settings
markdown: kramdown

